version: "3.8"

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - uploads_data:/var/www/html/wp-content/uploads
      - ./wp-config.php:/var/www/html/wp-config-sample.php

volumes:
  uploads_data:
